# Commits in feature branches will run linting and testing jobs.
# PRs targeting the main branch will run the full pre-PR checks.
name: Pre-PR Checks

on:
  push:
    branches:
      - '**'  # Runs on all branches (for commits)
  pull_request:
    branches:
      - main  # Runs on PRs targeting the main branch

jobs:
  # Linting job runs on all branches (including feature branches)
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run linting
        run: |
          black ./ --check --verbose
          flake8 --verbose

  # Testing job runs on all branches (including feature branches)
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run tests with coverage
        run: |
          pytest

  # Secrets scanning job runs only on PRs targeting main
  secrets-scanning:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - uses: actions/checkout@v3
      - name: Scan for secrets using GitHub's secret scanning
        uses: github/codeql-action/autobuild@v2
        with:
          language: python  # Change this based on your repo's language
      - name: Check for secrets in commit
        run: |
          curl -sSL https://raw.githubusercontent.com/awslabs/git-secrets/master/git-secrets | bash
          git secrets --scan

  # Vulnerability scanning job runs only on PRs targeting main
  vulnerability-scanning:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - uses: actions/checkout@v3
      - name: Scan for vulnerabilities with OWASP Dependency-Check
        uses: aquasecurity/trivy-action@v0.0.13
        with:
          scan-type: 'dependencies'
          severity: 'high,critical'
      - name: Show Trivy report
        run: |
          cat trivy-report.json

  # Full Pre-PR checks (runs only on PRs targeting main)
  pre-pr-checks:
    runs-on: ubuntu-latest
    needs: [lint, test, secrets-scanning, vulnerability-scanning]
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Notify Success
        run: echo "All pre-PR checks passed successfully."
